import Script from "next/script";
import "./globals.css";

export const metadata = {
    title: "MLST Live Stream",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={` antialiased`}>
                {children}
                <Script
                    src="https://players.brightcove.net/3745659807001/hXGs3fyvO_default/index.min.js"
                    strategy="afterInteractive"
                />
            </body>
        </html>
    );
}
