import Script from "next/script";
import "./globals.css";

export const metadata = {
    title: "MLST Live Stream",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={` antialiased`}>
                <Script id="google-tag-manager" strategy="beforeInteractive">{`
         (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','G-034XRGX66F');
        `}</Script>
                {children}
                <Script
                    src="https://players.brightcove.net/3745659807001/hXGs3fyvO_default/index.min.js"
                    strategy="afterInteractive"
                />
            </body>
        </html>
    );
}
